// src/app/components/course-filters/course-filters.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-course-filters',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatIconModule
  ],
  template: `
    <mat-card class="mb-6" style="border: 1px solid #e3f2fd;">
      <mat-card-content class="p-6">
        <div style="display: grid; grid-template-columns: 1fr; gap: 16px;">
          <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 16px;">
            <mat-form-field appearance="outline">
              <mat-label>Buscar cursos</mat-label>
              <input 
                matInput 
                [(ngModel)]="searchQuery" 
                (ngModelChange)="searchChange.emit($event)"
                placeholder="Buscar cursos..."
              >
              <mat-icon matSuffix>search</mat-icon>
            </mat-form-field>
            
            <mat-form-field appearance="outline">
              <mat-label>Categoría</mat-label>
              <mat-select 
                [(value)]="selectedCategory" 
                (selectionChange)="categoryChange.emit($event.value)"
              >
                @for (category of categories; track category) {
                  <mat-option [value]="category">{{ category }}</mat-option>
                }
              </mat-select>
            </mat-form-field>
            
            <mat-form-field appearance="outline">
              <mat-label>Nivel</mat-label>
              <mat-select 
                [(value)]="selectedLevel" 
                (selectionChange)="levelChange.emit($event.value)"
              >
                @for (level of levels; track level) {
                  <mat-option [value]="level">{{ level }}</mat-option>
                }
              </mat-select>
            </mat-form-field>
          </div>
        </div>
      </mat-card-content>
    </mat-card>
  `,
  styles: []
})
export class CourseFiltersComponent {
  @Output() searchChange = new EventEmitter<string>();
  @Output() categoryChange = new EventEmitter<string>();
  @Output() levelChange = new EventEmitter<string>();

  searchQuery = '';
  selectedCategory = 'Todas';
  selectedLevel = 'Todos';

  categories = ['Todas', 'Programación', 'Diseño', 'Marketing', 'Negocios', 'Idiomas'];
  levels = ['Todos', 'Principiante', 'Intermedio', 'Avanzado'];
}

// src/components/courses/CourseFilters.tsx

import React from 'react';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Search } from 'lucide-react';

interface CourseFiltersProps {
  searchQuery: string;
  onSearchChange: (query: string) => void;
  selectedCategory: string;
  onCategoryChange: (category: string) => void;
  selectedLevel: string;
  onLevelChange: (level: string) => void;
}

const categories = ['Todas', 'Programación', 'Diseño', 'Marketing', 'Negocios', 'Idiomas'];
const levels = ['Todos', 'Principiante', 'Intermedio', 'Avanzado'];

const CourseFilters = ({
  searchQuery,
  onSearchChange,
  selectedCategory,
  onCategoryChange,
  selectedLevel,
  onLevelChange
}: CourseFiltersProps) => {
  return (
    <div className="bg-white p-6 rounded-lg shadow-sm border border-blue-100 mb-6">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
          <Input
            placeholder="Buscar cursos..."
            value={searchQuery}
            onChange={(e) => onSearchChange(e.target.value)}
            className="pl-10 border-blue-200 focus:border-blue-500"
          />
        </div>
        
        <Select value={selectedCategory} onValueChange={onCategoryChange}>
          <SelectTrigger className="border-blue-200 focus:border-blue-500">
            <SelectValue placeholder="Categoría" />
          </SelectTrigger>
          <SelectContent>
            {categories.map((category) => (
              <SelectItem key={category} value={category}>
                {category}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        
        <Select value={selectedLevel} onValueChange={onLevelChange}>
          <SelectTrigger className="border-blue-200 focus:border-blue-500">
            <SelectValue placeholder="Nivel" />
          </SelectTrigger>
          <SelectContent>
            {levels.map((level) => (
              <SelectItem key={level} value={level}>
                {level}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>
    </div>
  );
};

export default CourseFilters;
